name: build-windows-exe
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -U pip pyinstaller
      - run: pip install -r requirements.txt
      - run: pyinstaller --onefile --windowed --name RecortarImgsGUI recortar_imgs_menu.py
      - uses: actions/upload-artifact@v4
        with:
          name: RecortarImgsGUI
          path: dist/RecortarImgsGUI.exe
